development:
  adapter: postgresql
  database: everquote_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: everquote_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: everquote_prod
  pool: 5
  timeout: 5000